services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: b3user
      POSTGRES_PASSWORD: b3pass
      POSTGRES_DB: b3analysis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
